# Generated by Django 4.1.3 on 2022-12-31 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CannedResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("response_template_name", models.CharField(max_length=255, verbose_name="Response Template Name")),
                ("path", models.CharField(max_length=1023, verbose_name="Path")),
            ],
        ),
        migrations.CreateModel(
            name="CannedResponseHeader",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Header Name")),
                ("value", models.TextField(verbose_name="Header Value")),
                (
                    "response",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="headers", to="example_response.cannedresponse"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BodyMatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("match_pattern", models.TextField(verbose_name="Regex Pattern to Search")),
                (
                    "canned_response",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="body_matches", to="example_response.cannedresponse"),
                ),
            ],
        ),
    ]
